version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odooDB
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:16
    command: odoo -d odooDB --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo -i base
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo/filestore

volumes:
  db-data:
  odoo-data:
